"""주식 슬리브 종목별 배분(Tier 2) + 가격 트리거 + 기업 100점 스코어링/DCF 도메인."""

from pams.equity.domain.allocation import (
    EvaluateStockAllocation,
    StockAllocationReport,
    StockAllocationRow,
    StockSignal,
    StockTarget,
    StockTargetPlan,
)
from pams.equity.domain.buy_gate import BuyGateCondition, BuyGateResult, evaluate_buy_gate
from pams.equity.domain.dcf import (
    DcfAssumptions,
    DcfResult,
    TriggerZones,
    ValuationError,
    ValuationGap,
    calculate_dcf,
    dcf_sensitivity,
    project_fcf,
    trigger_zones,
    valuation_gap,
)
from pams.equity.domain.financial_statement import (
    AnnualFinancials,
    AnnualFinancialsResult,
    FinancialStatementProvider,
    FinancialStatementProviderError,
)
from pams.equity.domain.growth_metrics import GrowthMetrics, compute_growth_metrics
from pams.equity.domain.score import (
    CategoryScore,
    CompanyScoreReport,
    ScoreItem,
    Verdict,
    verdict_for,
)
from pams.equity.domain.scoring_config import EntryBarrierConfig, RiskConfig, ScoringConfig
from pams.equity.domain.scoring_engine import (
    CompanyScoreInputs,
    RiskDeduction,
    score_company,
    score_competitiveness,
    score_financials,
    score_growth,
    score_risk,
    score_valuation,
)
from pams.equity.domain.trigger import (
    EvaluatePriceTriggers,
    PriceTrigger,
    PriceTriggerPlan,
    PriceTriggerReport,
    PriceTriggerRow,
    band_trigger,
)

__all__ = [
    "AnnualFinancials",
    "AnnualFinancialsResult",
    "BuyGateCondition",
    "BuyGateResult",
    "CategoryScore",
    "CompanyScoreInputs",
    "CompanyScoreReport",
    "DcfAssumptions",
    "DcfResult",
    "EntryBarrierConfig",
    "EvaluatePriceTriggers",
    "EvaluateStockAllocation",
    "FinancialStatementProvider",
    "FinancialStatementProviderError",
    "GrowthMetrics",
    "PriceTrigger",
    "PriceTriggerPlan",
    "PriceTriggerReport",
    "PriceTriggerRow",
    "RiskConfig",
    "RiskDeduction",
    "ScoreItem",
    "ScoringConfig",
    "StockAllocationReport",
    "StockAllocationRow",
    "StockSignal",
    "StockTarget",
    "StockTargetPlan",
    "TriggerZones",
    "ValuationError",
    "ValuationGap",
    "Verdict",
    "band_trigger",
    "calculate_dcf",
    "compute_growth_metrics",
    "dcf_sensitivity",
    "evaluate_buy_gate",
    "project_fcf",
    "score_company",
    "score_competitiveness",
    "score_financials",
    "score_growth",
    "score_risk",
    "score_valuation",
    "trigger_zones",
    "valuation_gap",
    "verdict_for",
]
